# Generated by Django 4.2.3 on 2023-08-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=100),
        ),
    ]
